---
- name: Bash deployment for Proxmox
  hosts: prox
  tasks:
    - name: Gather storage information from Proxmox
      ansible.builtin.command: pvesm zfsscan
      register: zpool
    - name: Print storage information from Proxmox
      ansible.builtin.debug: msg="Your zfs pool is {{ zpool.stdout }}"
    - name: Create zfs device from zpool
      ansible.builtin.command: pvesm add zfspool {{ item }} --pool {{ zpool.stdout }}
      with_items:
      - ansible
      ignore_errors: true
    - name: Check on progress
      ansible.builtin.command: pvesm status
      register: zfsstatus
    - name: Print status
      ansible.builtin.debug: msg="{{ zfsstatus.stdout_lines }}"
    - name: Create a fedora container
      community.general.proxmox:
        api_host: "{{ ansible_host }}"
        api_user: root@pam
        api_password: 1qaz2wsx!QAZ@WSX
        node: nerd
        password: 123456
        hostname: ansible.nerd.cpb.mil
        ostemplate: local:vztmpl/fedora-38-default_20230607_amd64.tar.xz
        storage: ansible
        cores: 1
        cpus: 1
        memory: 512
        swap: 512
        netif: '{"net0":"name=eth0,bridge=vmbr0,firewall=1"}'
        features:
          - nesting=1
        unprivileged: true
        description: CREATED WITH ANSIBLE
      changed_when: true
    - name: Start the container
      community.general.proxmox:
        api_host: "{{ ansible_host }}"
        api_user: root@pam
        api_password: 1qaz2wsx!QAZ@WSX
        vmid: 102
        state: started
      changed_when: true