---
- name: System tear down for Proxmox
  hosts: prox
  tasks:
    - name: Gather storage information from Proxmox
      ansible.builtin.command: pvesm zfsscan
      register: zpool
    - name: Print storage information from Proxmox
      ansible.builtin.debug: msg="Your zfs pool is {{ zpool }}"
    - name: Remove zfs device from zpool
      ansible.builtin.command: pvesm remove zfspool {{ item }} --pool {{ zpool.stdout }}
      with_items:
      - kube
      - lima
      - zed
      - quin
      - kevi
      ignore_errors: true
    - name: Check on progress
      ansible.builtin.command: pvesm status
      register: zfsstatus
    - name: Print status
      ansible.builtin.debug: msg="{{ zfsstatus }}"