---
- name: Install kubernetes tools
  hosts: kubernetes
  become: true
  become_user: root
  tasks:
  - name: Copy the kubernetes repo file
    copy:
      src: /home/bobbymayyy/Kube/ansible/playbooks/kubernetes_setup/kubernetes.repo
      dest: /etc/yum.repos.d/kubernetes.repo
  - name: Set SELinux in permissive mode
    selinux:
      policy: targeted
      state: permissive
  - name: Disable firewalld
    service:
      name: firewalld
      state: stopped
      enabled: false
  - name: Install kubeadm, kubectl and kubelet
    dnf:
      name: '{{ item  }}'
      state: present
      disable_excludes: kubernetes
    with_items:
     - kubeadm
     - kubectl
     - kubelet
  - name: Enable and start the kubelet service
    service:
      name: kubelet
      state: started
      enabled: yes
  - name: Disable SWAP since kubernetes can't work with SWAP enabled
    shell: |
      swapoff -a
      sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  - name: Disable zram specific to fedora
    dnf:
      name: zram-generator-defaults
      state: absent