---
- name: Deployment of Security Onion cluster by template backup
  hosts: prox_master
  tasks:
    - name: Get hostname for later use
      ansible.builtin.command: hostname
      register: proxHostname
    - name: Restore SecO VM from backup template for Manager
      ansible.builtin.command: qmrestore --unique true /var/lib/vz/dump/vzdump-qemu-100-2023_11_27-12_16_57.vma.zst 110
      register: secOmanagerTemprestore
      ignore_errors: True
    - name: Print secOmanagerTemprestore
      ansible.builtin.debug: msg="{{ secOmanagerTemprestore.stdout_lines }}"
    - name: Restore SecO VM from backup template for Search
      ansible.builtin.command: qmrestore --unique true /var/lib/vz/dump/vzdump-qemu-100-2023_11_27-12_20_23.vma.zst 111
      register: secOsearchTemprestore
      ignore_errors: True
    - name: Print secOsearchTemprestore
      ansible.builtin.debug: msg="{{ secOsearchTemprestore.stdout_lines }}"
    - name: Restore SecO VM from backup template for Forward
      ansible.builtin.command: qmrestore --unique true /var/lib/vz/dump/vzdump-qemu-100-2023_11_27-12_23_12.vma.zst 112
      register: secOforwardTemprestore
      ignore_errors: True
    - name: Print secOforwardTemprestore
      ansible.builtin.debug: msg="{{ secOforwardTemprestore.stdout_lines }}"
    - name: Pause for 30 seconds to wait for restore
      ansible.builtin.pause:
        seconds: 30
    - name: Start SecO Manager VM
      community.general.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: root@pam
        api_password: "{{ ansible_password }}"
        name: SecOManager
        vmid: 110
        node: "{{ proxHostname.stdout }}"
        state: started
      changed_when: true
    - name: Start SecO Search VM
      community.general.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: root@pam
        api_password: "{{ ansible_password }}"
        name: SecOSearch
        vmid: 111
        node: "{{ proxHostname.stdout }}"
        state: started
      changed_when: true
    - name: Start SecO Forward VM
      community.general.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: root@pam
        api_password: "{{ ansible_password }}"
        name: SecOForward
        vmid: 112
        node: "{{ proxHostname.stdout }}"
        state: started
      changed_when: true
    - name: Pause for 90 seconds to wait for boot
      ansible.builtin.pause:
        seconds: 90