---
- name: Deployment of Security Onion cluster by template backup
  hosts: prox_master
  tasks:
    - name: Get hostname for later use
      ansible.builtin.command: hostname
      register: proxHostname
    - name: Restore SecO VM from backup template for Manager
      ansible.builtin.command: qmrestore /var/lib/vz/dump/vzdump-qemu-100-2023_11_27-05_56_29.vma.zst 110
      register: secOmanagerTemprestore
      ignore_errors: True
    - name: Print secOmanagerTemprestore
      ansible.builtin.debug: msg="{{ secOmanagerTemprestore.stdout_lines }}"
    - name: Restore SecO VM from backup template for Search
      ansible.builtin.command: qmrestore /var/lib/vz/dump/vzdump-qemu-100-2023_11_27-06_00_34.vma.zst 111
      register: secOsearchTemprestore
      ignore_errors: True
    - name: Print secOsearchTemprestore
      ansible.builtin.debug: msg="{{ secOsearchTemprestore.stdout_lines }}"
    - name: Restore SecO VM from backup template for Search 2
      ansible.builtin.command: qmrestore /var/lib/vz/dump/vzdump-qemu-100-2023_11_27-06_00_34.vma.zst 112
      register: secOsearch2Temprestore
      ignore_errors: True
    - name: Print secOsearch2Temprestore
      ansible.builtin.debug: msg="{{ secOsearch2Temprestore.stdout_lines }}"
    - name: Restore SecO VM from backup template for Forward
      ansible.builtin.command: qmrestore /var/lib/vz/dump/vzdump-qemu-100-2023_11_27-06_11_33.vma.zst 113
      register: secOforwardTemprestore
      ignore_errors: True
    - name: Print secOforwardTemprestore
      ansible.builtin.debug: msg="{{ secOforwardTemprestore.stdout_lines }}"
    - name: Restore SecO VM from backup template for Forward 2
      ansible.builtin.command: qmrestore /var/lib/vz/dump/vzdump-qemu-100-2023_11_27-06_11_33.vma.zst 114
      register: secOforward2Temprestore
      ignore_errors: True
    - name: Print secOforward2Temprestore
      ansible.builtin.debug: msg="{{ secOforward2Temprestore.stdout_lines }}"
    - name: Restore SecO VM from backup template for Forward 3
      ansible.builtin.command: qmrestore /var/lib/vz/dump/vzdump-qemu-100-2023_11_27-06_11_33.vma.zst 115
      register: secOforward3Temprestore
      ignore_errors: True
    - name: Print secOforward3Temprestore
      ansible.builtin.debug: msg="{{ secOforward3Temprestore.stdout_lines }}"
    - name: Restore SecO VM from backup template for Forward 4
      ansible.builtin.command: qmrestore /var/lib/vz/dump/vzdump-qemu-100-2023_11_27-06_11_33.vma.zst 116
      register: secOforward4Temprestore
      ignore_errors: True
    - name: Print secOforward4Temprestore
      ansible.builtin.debug: msg="{{ secOforward4Temprestore.stdout_lines }}"
    - name: Restore SecO VM from backup template for Forward 5
      ansible.builtin.command: qmrestore /var/lib/vz/dump/vzdump-qemu-100-2023_11_27-06_11_33.vma.zst 117
      register: secOforward5Temprestore
      ignore_errors: True
    - name: Print secOforward5Temprestore
      ansible.builtin.debug: msg="{{ secOforward5Temprestore.stdout_lines }}"
    - name: Pause for 30 seconds to wait for restore
      ansible.builtin.pause:
        seconds: 30
    - name: Start SecO Manager VM
      community.general.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: root@pam
        api_password: "{{ ansible_password }}"
        name: SecOManager
        vmid: 110
        node: "{{ proxHostname.stdout }}"
        state: started
      changed_when: true
    - name: Start SecO Search VM
      community.general.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: root@pam
        api_password: "{{ ansible_password }}"
        name: SecOSearch
        vmid: 111
        node: "{{ proxHostname.stdout }}"
        state: started
      changed_when: true
    - name: Start SecO Search 2 VM
      community.general.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: root@pam
        api_password: "{{ ansible_password }}"
        name: SecOSearch
        vmid: 112
        node: "{{ proxHostname.stdout }}"
        state: started
      changed_when: true
    - name: Start SecO Forward VM
      community.general.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: root@pam
        api_password: "{{ ansible_password }}"
        name: SecOForward
        vmid: 113
        node: "{{ proxHostname.stdout }}"
        state: started
      changed_when: true
    - name: Start SecO Forward 2 VM
      community.general.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: root@pam
        api_password: "{{ ansible_password }}"
        name: SecOForward
        vmid: 114
        node: "{{ proxHostname.stdout }}"
        state: started
      changed_when: true
    - name: Start SecO Forward 3 VM
      community.general.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: root@pam
        api_password: "{{ ansible_password }}"
        name: SecOForward
        vmid: 115
        node: "{{ proxHostname.stdout }}"
        state: started
      changed_when: true
    - name: Start SecO Forward 4 VM
      community.general.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: root@pam
        api_password: "{{ ansible_password }}"
        name: SecOForward
        vmid: 116
        node: "{{ proxHostname.stdout }}"
        state: started
      changed_when: true
    - name: Start SecO Forward 5 VM
      community.general.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: root@pam
        api_password: "{{ ansible_password }}"
        name: SecOForward
        vmid: 117
        node: "{{ proxHostname.stdout }}"
        state: started
      changed_when: true
    - name: Pause for 90 seconds to wait for boot
      ansible.builtin.pause:
        seconds: 90