---
- name: Initialize kubernetes infra
  hosts: master  #Kube master
  become: true
  become_user: root
  tasks:
  - name: Edit toml for containerd
    replace:
      path: /etc/containerd/config.toml
      regexp: disabled_plugins = \["cri"\]
      replace: enabled_plugins = ["cri"]\n[plugins."io.containerd.grpc.v1.cri".containerd]\nendpoint = "unix:///var/run/containerd/containerd.sock"
  - name: Create cni net.d directory
    file:
      path: /etc/cni/net.d
      state: directory
      mode: 0755
  - name: Template cni config
    template:
      src: ../templates/10-containerd-net.conflist.j2
      dest: /etc/cni/net.d/10-containerd-net.conflist
      owner: root
      group: root
      mode: 0644
  - name: Restart containerd
    service:
      name: containerd
      state: restarted
  - name: Initialize kubernetes cluster #Default is 10.244.0.0/16
    shell: |
      kubeadm init --pod-network-cidr=10.244.0.0/16
    register: init_output
  - name: Print the initialization output
    debug: msg="{{ init_output }}"