---
- name: Deploy flannel networking policy
  hosts: master #Kube master
  tasks:
  - name: Wait a bit...
    pause:
      seconds: 60
  - name: Create /opt/cni/bin
    file:
      path: /opt/cni/bin
      state: directory
      mode: 0755
  - name: Download cni binaries
    shell: curl -O -L https://github.com/containernetworking/plugins/releases/download/v1.2.0/cni-plugins-linux-amd64-v1.2.0.tgz
  - name: Uncompress to proper location
    shell: tar -C /opt/cni/bin -xzf cni-plugins-linux-amd64-v1.2.0.tgz
  - name: Apply the flannel networking policy definition
    shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  - name: Get the token for joining the worker nodes
    shell: kubeadm token create --print-join-command
    register: kubernetes_join_command
  - name: Print the kubernetes node join command
    debug:
      msg: "{{ kubernetes_join_command.stdout }}"
  - name: Copy join command to local file
    local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777