---
- name: Reset cluster using kubeadm and cleanup
  hosts: kubernetes
  become: true
  become_user: root
  tasks:
  - name: Reset
    command:
      cmd: kubeadm reset -f
    changed_when: true
  - name: Reset again for good measure
    command:
      cmd: kubeadm reset -f
    changed_when: true
  - name: Destroy contents of /var/log/kubernetes
    shell:
      cmd: rm -rf /var/log/kubernetes/*
    changed_when: true
  - name: Stop the kubelet service
    service:
      name: kubelet
      state: stopped
  - name: Stop containerd
    service:
      name: containerd.service
      state: stopped